### ISSUE TITLE
Update fleet page

### ISSUE THREAD

**Issue by TStickney** [UnicornUnited/DuckDuckGoose#41]
Shows all the airplanes as a grid or table. The planes should link to their plane data page. 
When user is admin, then the fields are editable, and users should only be able to read.

**Comment by TakitoCabrera** [comment]
To Do:
- Need to figure out a way for CSV to update when submit button is clicked.
- Add plane identifier. This should send to plane page when clicked (Guest role I assume)
- Add button to be included so more fields can be added

**Comment by TakitoCabrera** [comment]
To Do:
- Add plane identifier. This should send to plane page when clicked (Guest role I assume)
- Add button to be included so more fields can be added
