### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by TakitoCabrera** [UnicornUnited/DuckDuckGoose#75]
- Unit testing is isolated from the program code.
- If testing doesn't pass in Unit testing, the web app should also not accept the input
- Unit Testing should be dealt by each individual. Please let the team know ASAP if you need any help

**Comment by JaydenLiang** [comment]
These functions can help in business logic testing against budget.
FleetModel->getBudget() 
FleetModel->getGrandTotal()
